// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function AddProdutoMateriaPrimaByName(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GetItemIDByName(arg1:string):Promise<number>;

export function GetItems():Promise<Array<{[key: string]: any}>>;

export function GetMateriasPrimasPorProdutoByName(arg1:string):Promise<Array<{[key: string]: any}>>;

export function Greet(arg1:string):Promise<string>;
