// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddItem'](arg1, arg2, arg3, arg4);
}

export function AddProdutoMateriaPrimaByName(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProdutoMateriaPrimaByName'](arg1, arg2, arg3);
}

export function GetItemIDByName(arg1) {
  return window['go']['main']['App']['GetItemIDByName'](arg1);
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetMateriasPrimasPorProdutoByName(arg1) {
  return window['go']['main']['App']['GetMateriasPrimasPorProdutoByName'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
